name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Diff
      run: for f in testbench/* ; do echo $f ; do echo "\n\n" ; do bash diff.sh $f ; do echo "\n" ; done ;
